{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kilnAPI.fullname" . }}-nginx-svc
  labels:
    app.kubernetes.io/name: {{ include "kilnAPI.name" . }}-nginx
    {{- include "kilnAPI.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "kilnAPI.name" . }}-nginx
  ports:
    {{- range $name, $port := .Values.nginx.service.ports }}
    - name: {{ $name }}
      port: {{ $port }}
      targetPort: http
      protocol: TCP
    {{- end }}
{{- end }}
